### ISSUE TITLE
Admin notices and login message are not being translated.

### ISSUE THREAD

**Issue by freemp** [wpdocde/slim-maintenance-mode#2]

**Comment by wpdocde** [comment]
Thank you for opening this issue. Can you provide more detailed information to your concern, especially which language you want to use?

**Comment by freemp** [comment]
When in maintenance mode, all messages provided in the admin area are displayed in English language only. None of the available translations are being loaded. The maintenance message itself, displayed to visitors while the plugin is activated is being displayed correctly with translations provided.
The cause of the problem is the way translations are applied. For more details, please find the fix provided with my pull-request.

**Comment by wpdocde** [comment]
Thank you very much. I merged your proposal and will test it.

**Comment by wpdocde** [comment]
Will be fixed in version 1.3.

**Comment by freemp** [comment]
Thank you for providing this plugin. I like it very much for its simplicity.
