### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by frysco** [wpdocde/slim-maintenance-mode#4]
Fatal error: Invalid opcode 153/1/8. in /home/marcabr/public_html/pt/wp-content/plugins/slim-maintenance-mode/slim-maintenance-mode.php on line 90

**Comment by wpdocde** [comment]
Thank you for your notice. Can you provide some additional information, please? I can´t reproduce this error.

**Comment by wpdocde** [comment]
Seems that this error is not generated by the plugin.
